In [1]:
import import_ipynb
import numpy as np, pandas as pd
import cv2, time, os

In [2]:
face_detect = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

# Loading or Generating Data to Train the Model:

In [3]:
path = 'data_for_training'
dir = os.listdir(path)

if len(dir) != 0:
    input_images = []
    targets = []
    for images in dir:
        filename = path + '/' + images
        face = cv2.imread(filename)
        gray = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)
        input_images.append(gray)
        targets.append(int(images.split('-')[1].split('.')[0]))
    print("Data loaded Successfully!")
    
else:
    print("Data unavailable for training. Scan of your face needed.")
    time.sleep(0.5)
    members = int(input("Mention the no. of members: "))
    source = cv2.VideoCapture(0)
    input_images = []
    targets = []
    counter = 0
    for i in range(members):
        no_of_images = 0
        input('Press enter to start capturing')
        print("Get ready, scanning your face in 5 seconds.")
        time.sleep(5)
        while True:
            _, image = source.read(0)
            gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
            # detecting faces
            detected_faces = face_detect.detectMultiScale(gray, 1.2, 9)
            
            if len(detected_faces) > 1:
                continue
            else:
                pass
            
            for bbox in detected_faces:
                x,y,w,h = bbox

                # croping the faces for training the model
                cropped_image = cv2.resize(gray[y:y+h,x:x+w],(100,100))
                input_images.append(cropped_image)
                targets.append(counter)
                
                # Saving input_images for future use
                no_of_images += 1
                path = 'data_for_training'
                cv2.imwrite(os.path.join(path , str(no_of_images) + '-' + str(counter)+'.jpg'), cropped_image)

                # Formatting image for display
                cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 3)
                cv2.putText(image, "Image No : " + str(no_of_images), (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 100, 100), 2)
                cv2.imshow("Scanning your face", image)
                cv2.waitKey(1)
            if no_of_images == 500:
                break
        
        counter += 1
        
        cv2.destroyAllWindows()
    source.release()

Data loaded Successfully!


In [4]:
input_images

[array([[153, 154, 155, ..., 130, 149, 153],
        [153, 153, 154, ..., 105, 135, 148],
        [153, 153, 152, ...,  99, 128, 152],
        ...,
        [147, 148, 149, ..., 154, 154, 153],
        [147, 147, 149, ..., 154, 154, 153],
        [148, 153, 165, ..., 152, 152, 152]], dtype=uint8),
 array([[144, 144, 144, ..., 143, 142, 142],
        [143, 146, 143, ..., 144, 143, 142],
        [143, 147, 142, ..., 143, 142, 142],
        ...,
        [143, 142, 144, ..., 176, 163, 154],
        [139, 151, 166, ..., 186, 180, 171],
        [171, 188, 200, ..., 189, 189, 182]], dtype=uint8),
 array([[ 36,  36,  35, ..., 160, 160, 159],
        [ 34,  41,  48, ..., 159, 159, 159],
        [ 37,  42,  53, ..., 159, 159, 158],
        ...,
        [148, 148, 148, ..., 152, 152, 152],
        [148, 148, 148, ..., 153, 152, 152],
        [148, 148, 147, ..., 153, 153, 152]], dtype=uint8),
 array([[150, 149, 149, ..., 152, 149, 155],
        [151, 150, 148, ..., 153, 151, 153],
        [153, 15

In [5]:
targets

[0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,


In [6]:
print("Input Image Count : ", len(input_images))
print("Target Count : ", len(targets))

Input Image Count :  2000
Target Count :  2000


# Preparing the Data for Training the Neural Network:

In [7]:
input_images_normalized = np.array(input_images)/255.0
input_images_normalized

array([[[0.6       , 0.60392157, 0.60784314, ..., 0.50980392,
         0.58431373, 0.6       ],
        [0.6       , 0.6       , 0.60392157, ..., 0.41176471,
         0.52941176, 0.58039216],
        [0.6       , 0.6       , 0.59607843, ..., 0.38823529,
         0.50196078, 0.59607843],
        ...,
        [0.57647059, 0.58039216, 0.58431373, ..., 0.60392157,
         0.60392157, 0.6       ],
        [0.57647059, 0.57647059, 0.58431373, ..., 0.60392157,
         0.60392157, 0.6       ],
        [0.58039216, 0.6       , 0.64705882, ..., 0.59607843,
         0.59607843, 0.59607843]],

       [[0.56470588, 0.56470588, 0.56470588, ..., 0.56078431,
         0.55686275, 0.55686275],
        [0.56078431, 0.57254902, 0.56078431, ..., 0.56470588,
         0.56078431, 0.55686275],
        [0.56078431, 0.57647059, 0.55686275, ..., 0.56078431,
         0.55686275, 0.55686275],
        ...,
        [0.56078431, 0.55686275, 0.56470588, ..., 0.69019608,
         0.63921569, 0.60392157],
        [0.5

In [8]:
input_images_normalized_reshaped = input_images_normalized.reshape(len(input_images_normalized),100,100,1)
input_images_normalized_reshaped

array([[[[0.6       ],
         [0.60392157],
         [0.60784314],
         ...,
         [0.50980392],
         [0.58431373],
         [0.6       ]],

        [[0.6       ],
         [0.6       ],
         [0.60392157],
         ...,
         [0.41176471],
         [0.52941176],
         [0.58039216]],

        [[0.6       ],
         [0.6       ],
         [0.59607843],
         ...,
         [0.38823529],
         [0.50196078],
         [0.59607843]],

        ...,

        [[0.57647059],
         [0.58039216],
         [0.58431373],
         ...,
         [0.60392157],
         [0.60392157],
         [0.6       ]],

        [[0.57647059],
         [0.57647059],
         [0.58431373],
         ...,
         [0.60392157],
         [0.60392157],
         [0.6       ]],

        [[0.58039216],
         [0.6       ],
         [0.64705882],
         ...,
         [0.59607843],
         [0.59607843],
         [0.59607843]]],


       [[[0.56470588],
         [0.56470588],
         [0.56

In [9]:
# For One-Hot Encoding:

from keras.utils import np_utils
targets = np_utils.to_categorical(targets)
targets

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [10]:
from sklearn.model_selection import train_test_split

X_TRAIN, X_TEST, Y_TRAIN, Y_TEST = train_test_split(input_images_normalized_reshaped, targets)

# Building and Training the Neural Network:

In [11]:
from keras.models import Sequential
from keras.layers import Conv2D, Dense, Activation, Flatten
from keras.callbacks import ModelCheckpoint

In [12]:
model = Sequential()

model.add(Conv2D(300, (3, 3), input_shape = (100, 100, 1)))
model.add(Activation('relu'))

model.add(Conv2D(100, (3,3)))
model.add(Activation('relu'))

model.add(Flatten())

model.add(Dense(50, activation='relu'))
model.add(Dense(len(targets[0]), activation='softmax'))

model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['categorical_accuracy'])

### Defining Checkpoint and Training the Model:

In [13]:
cp = ModelCheckpoint('best_one', verbose=0, save_best_only=True)
model.fit(X_TRAIN, Y_TRAIN, epochs = 4, callbacks=[cp], validation_split=0.2)

Epoch 1/4
38/38 [==============================] - 116s 3s/step - loss: 3.9565 - categorical_accuracy: 0.5198 - val_loss: 0.0049 - val_categorical_accuracy: 0.9967
INFO:tensorflow:Assets written to: best_one\assets
Epoch 2/4
38/38 [==============================] - 102s 3s/step - loss: 0.0081 - categorical_accuracy: 0.9967 - val_loss: 9.5027e-04 - val_categorical_accuracy: 1.0000
INFO:tensorflow:Assets written to: best_one\assets
Epoch 3/4
38/38 [==============================] - 103s 3s/step - loss: 1.0465e-04 - categorical_accuracy: 1.0000 - val_loss: 2.5083e-05 - val_categorical_accuracy: 1.0000
INFO:tensorflow:Assets written to: best_one\assets
Epoch 4/4
38/38 [==============================] - 105s 3s/step - loss: 5.6254e-05 - categorical_accuracy: 1.0000 - val_loss: 9.6815e-05 - val_categorical_accuracy: 1.0000


In [14]:
from keras.models import load_model
model = load_model('best_one')

In [15]:
model.predict(X_TEST)

array([[1.2721620e-17, 1.0000000e+00, 9.9371134e-14, 1.2832076e-15],
       [1.4045396e-06, 3.8178946e-08, 9.9999857e-01, 7.3038842e-10],
       [3.0417161e-07, 6.7474694e-08, 9.9999952e-01, 7.1570298e-08],
       ...,
       [9.9999988e-01, 2.3621637e-13, 1.0688097e-07, 5.1623470e-08],
       [9.9999547e-01, 2.5556198e-11, 8.2528533e-07, 3.7240497e-06],
       [1.2485944e-05, 4.1291648e-10, 4.1607384e-11, 9.9998748e-01]],
      dtype=float32)

# Defining function for Sending SMS:

In [16]:
import conf
from twilio.rest import Client

importing Jupyter notebook from conf.ipynb


#### Note: conf is the file containing personal data required for sending SMS

In [17]:
def send_twilio_alert(alert):
    account_sid = conf.SID
    auth_token = conf.AUTH_TOKEN
    TO_NUMBER = conf.TO_NUMBER
    FROM_NUMBER = conf.FROM_NUMBER
    client = Client(account_sid, auth_token) 
 
    message = client.messages.create(to = TO_NUMBER,from_ = FROM_NUMBER, body = alert)
    print(message.sid)

# Defining function for Alerting on Telegram:

In [18]:
import requests, json

In [19]:
def send_telegram_alert(alert):
    url = "https://api.telegram.org/bot" + conf.telegram_bot_id + "/sendMessage"
    data = {
        "chat_id": conf.telegram_chat_id,
        "text": alert
    }
    try:
        response = requests.request(
            "POST",
            url,
            params=data
        )
        telegram_data = json.loads(response.text)
        if telegram_data["ok"] == True:
            return "Alert Raised."
    except Exception as e:
        print("An error occurred in sending the alert message via Telegram")
        print(e)
        return False

# Initiating Surveillance:

In [20]:
from IPython.display import clear_output

In [34]:
source = cv2.VideoCapture(0)
while True:
    prob_is_me = []
    _, image = source.read()
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    # detecting faces
    detected_faces = face_detect.detectMultiScale(gray, 1.2, 9)
    
    if len(detected_faces) == 0:
        continue
    else:
        pass
    
    for each_face in detected_faces:

        x, y, w, h = each_face
        cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 3)
        # Cropping the image
        crop = gray[y:y+h, x:x+w]
        cropped_image = cv2.resize(crop, (100, 100))
        
        # Normalising and reshaping image
        normalized_image = cropped_image/255
        reshaped_face = np.reshape(normalized_image, (1, 100, 100, 1))
        
        # Displaying captured image
        cv2.imshow("Scanning your face", image)
        
        #Predicting and collecting results in a list
        result = model.predict(reshaped_face)[0]

        prob_is_me.append(result[0])
    print(prob_is_me)
   

    if max(prob_is_me) < 0.90:
        print("Someone unrecognized detected! Sending alerts.")
        #send_twilio_alert("Caution! Someone is trying to trespass the security. \n"
        #                 +"Number of intruders : " + str(len(prob_is_me)))
        telegram_status = send_telegram_alert(alert = "Caution! Someone is trying to trespass the security. \n"
                                             +"Number of intruders : " + str(len(prob_is_me)))
        print("Telegram Status: ", telegram_status)
        time.sleep(5)
    else:
        #time.sleep(7)
        pass
    
    time.sleep(0.5)
    clear_output(wait=True)   
    
    key = cv2.waitKey(1)
    if key == 27:
        break
    else:
        pass
cv2.destroyAllWindows()
source.release()

[0.5778148, 0.00043475645]
Someone unrecognized detected! Sending alerts.
Telegram Status:  Alert Raised.
